### ISSUE TITLE
Enhance CPE generation to improve downstream matching in grype

### ISSUE THREAD

**Issue by wagoodman** [anchore/syft#471]
After completing #396  there is room for further improvements to help with FP matches in grype.

- [x] Re-enable searching for jenkins (and other) plugins https://github.com/anchore/syft/blob/v0.19.1/syft/pkg/cataloger/cpe.go#L334 
- [x] Generate CPE candidates to attempt to match on umbrella projects from sub-component packages (e.g. match on a vendor of `cloudbees` from a package called `cloudbees-some-component`) based on hyphen/underscore splitting.
- [x] When generating vendors and products during CPE generation for java packages, both the artifactID and groupID should be used for both vendor and product values, not just artifactIDs for products and groupIDs for vendors in isolation.
- [x] Add “Extension-Name” and "Automatic-Module-Name" for groupID processing for java packages during CPE generation (a source for product and vendor information).
- [x] Add “ruby-lang” vendor value for gems.
